### ISSUE TITLE
Reconstruct a portion of a scan?

### ISSUE THREAD

**Issue by susannahammarberg** [ptycho/ptypy#109]
Say that I have made a large ptycho scan, and I want to try to reconstruct just a part of it; a section in the middle of the grid. When tunning ptypy, is there an easy way implemented to choose an interval of scanning positions?

Best,
Sanna

**Comment by simonesala** [comment]
Hi Sanna,
When it comes to coding time, the easiest way to tackle the issue you describe that comes to mind is to just turn off the views onto the object that you would like not to be used. This would be done within your launching script. So at its end, rather than having
P = Ptycho(p, level=5)
which would load the data and run the recons in one go, you would have something like this
P = Ptycho(p, level=2)
for sID, s in P.obj.S.iteritems():
    for v in s.views:
        if v.ID not in turned_off_views_ID:
            v.active = False
P.run()
which will turn off (set to False) all the views with IDs in the 'turned_off_views_ID' list. So you could just make a list of the indices you'd like to exclude and feed it in at any point. Keep in mind the IDs are something like 'V0000', 'V0001' and so on, so you'll need a list of such strings.

From my point of view, the main downside of this approach is that your script would be loading the full dataset which might be good for documentation and such but could take unnecessary time and memory.
An alternative would be to just rewrite a file containing only the desired frames which is anyway pretty close to finding the desired indices. Just pick your favourite approach.
Hope this helps.
Simone

**Comment by alexbjorling** [comment]
I also think this would be a useful feature. But rather than specifying which views/pods to use by index, you should be able to define regions in x and y.

Maybe it's complicated. Like Simone says, handling it at the script or `Ptycho` level would mean reading everything in first. One reason to reconstruct just a portion might be to run a preliminary analysis with limited memory or other resources. I guess it should be done at the `PtyScan` level. If `PtydScan` supported limited reconstruction regions then at least you could run from `ptyd` files, then it could be up to `PtyScan`authors to support it or not for the raw data part.

**Comment by bjoernenders** [comment]
Those are good ideas. Switching pods on or off depending on location has long been on our todo list. It has close ties with load-balancing. We would need to extent in what Alex did in the EPIE engine to a more general area labeling technique (ie. row, column, radial or angular or packing of spheres or rectangles) with also a weight on the processes.

Having a filter on PtyScan is a good idea as well but as @alexbjorling said, it should be a subclass feature for now.

**Comment by pierrethibault** [comment]
Now an enhancement issue: #116
