### ISSUE TITLE
The tests capture all the entries to the log, making it difficult to browse the tests.

### ISSUE THREAD

**Issue by bjoernenders** [ptycho/ptypy#159]
Maybe I'm stupid, but It's kind of hard to read the test log.

**Comment by aaron-parsons** [comment]
I see your point, but there are multiple options for this:
1/ we set the verbosity level in each test to be 0 to get rid of stout. I dislike this because it means we then have no idea what is happening.

2/ If you use an IDE and the test viewer in there, it uses the test report to make it clearer what is going on. You typically only get the stdout for the particular test you have selected.

3/ If you want to use pytest through the command line,  then there are some options here: https://gist.github.com/kwmiebach/3fd49612ef7a52b5ce3a to choose what you see.

I think I'll close this, and you can reopen if it continues to frustrate.
