### ISSUE TITLE
DM: different results depending on the number of probe modes

### ISSUE THREAD

**Issue by daurer** [ptycho/ptypy#169]
https://github.com/ptycho/ptypy/blob/094e272bf06d7e13757ece85c16969be2972853f/ptypy/engines/DM.py#L313

I am not quite sure if this is a bug, but I found that I am getting different results on the object depending on how many probe modes I am using. I noticed that the ```self.ob_viewcover.storages[name].data```  scales with the number of probe modes. This has an affect on the calculation of cfact in the object update.

**Comment by bjoernenders** [comment]
Hi Benedict,
thanks for pointing this bug out. Do you have a minimal script for reference, or does it work with a standard template? The behavior of this part of the code was last reviewed by @pierrethibault and he added the commit e5d8424 in September 2017. Maybe this helps figuring out what is going on.
Bjoern

**Comment by daurer** [comment]
You can reproduce this with the ```minimal_script.py``` inside tutorial. Turning on smoothing for DM, you can see that ```cfact``` changes depending on the number of probe modes. 

I think the issues is here when the view coverage is calculated: https://github.com/ptycho/ptypy/blob/094e272bf06d7e13757ece85c16969be2972853f/ptypy/core/classes.py#L910

As far as I can see the per-pixel views are extended depending on the number of modes, which then leads to a different view coverage depending on the nmodes. But for the object, the view coverage should always be the same.

**Comment by pierrethibault** [comment]
Good catch Benedikt. 

The idea is that `cfact` should be equal to `object_inertia` (our tweak parameter) times a quantity that is roughly equal to the local fluence. When running with a single mode, `mean_power*coverage` is roughly right (and the `+1` is to avoid dividing by 0), but since the power is divided between the modes and coverage scales like the number of modes, the scaling is off. The simple solution is to divide `cfact` by the number of modes, though this might not be the most robust approach since there might be funky cases were the probe views attached to a given diffraction pattern are not interpreted as modes. Since `DM.ob_viewcover` and `DM.mean_power` are essentially defined only for the purpose of computing `cfact`, there is probably a better way to do it. I'll look into that.

**Comment by jcesardasilva** [comment]
Thank you Benedikt,
I have observed this behavior too with my data in near-field ptychography,
specially when there is phase wrapping (the wrapping does not appear when
using mpi, but appears when using single core). I thought it was a mistake
of mine, but never had the time to check it. So, I am really glad you did
and that I am not alone.


Le mer. 12 sept. 2018 à 12:22, Pierre Thibault <notifications@github.com> a
écrit :

**Comment by bjoernenders** [comment]
Maybe we could just keep the Norm? That most accurately reflects the local fluence at the object. Currently we are initializing it at the beginning of each scan. We could use the view coverage only to initialize the norm at the beginning of DM.

**Comment by pierrethibault** [comment]
I have decided to remove the coverage part in the `cfact` calculation (commit 6ca024e). Though it might be a good idea, I believe that the coverage idea had never been totally tested, and the current implementation follows more closely the original philosophy.

@daurer: it would be great if you could give it a spin (including also the fix for #168).

**Comment by pierrethibault** [comment]
Benedikt privately confirmed that reconstructions are now stable w.r.t. number of nodes and modes.
