### ISSUE TITLE
Replace Param class with treedict

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#17]
Remains to check if we want treedict to be a dependency or if we integrate the code as submodule.

**Comment by stefanoschalkidis** [comment]
Hi all,
I've completed the core transition to TreeDict. (see latest commit on sc_dev). Preparing, loading and running DM and ML with i13dls_nfp should work, although I haven't fixed the error I get after preparing with MPI. Reconstruction scripts and PtyScan subclasses will require small adjustments (see scripts in provided link and i13dls_nfp subclass in experiment). The plotting client has not been adapted yet. The main idea was to replace every input parameter with a TreeDict branch. Instances where Param was just used for bookkeeping, e.g. in _pool, were not changed. 

Regarding TreeDict itself, I didn't find an easy way to include it into ptypy. Submoduling the repo and having it installed via distutils.core.run_setup or subprocess.call() didn't work well. I might try setuptools to see if it makes any difference. Pre-compiling and including as a lib led to pickling errors. Therefore I ended up using pip install treedict==0.2.2 (have to specify latest version otherwise it will get you the wrong one). Building from source also works.

Please find below the scripts and data I used (note that I'm using just 15 images to speed up things, for nicer recons use all 38) for testing and let me know how you would like to proceed with this.

https://www.dropbox.com/sh/ptvta736o15rok6/AAAsgz_7FhTTJ3FMvz5A35PHa?dl=0

**Comment by bjoernenders** [comment]
Hi Stefanos,

thank you for your work. I browsed through you commit. Unfortunanely it is entirely mixed up with PEP8 and formatting changes. It is very hard to see where it changed. Also as long as we cannot reliably include treedict, we cannot make the transition as it breaks backward compatibility. Please do not merge the branch to master for now. 
The setup.py of treedict looks pretty manual and messy and can probably be solved in a more, I'm confident we can exclude it in a good way. I suggest the following, Stefanos:
- make a commit with ONLY the PEP8 formatting changes to master.
- open a new branch with title 'target' as suggested by Pierre and commit the changes where treedict was used. Make sure, that only the treedict change is what separates it from master branch. 

Other opinions

**Comment by stefanoschalkidis** [comment]
Hi Bjoern,

Thanks a lot for your feedback. I agree that the PEP8 changes should have been a separate commit. I will try to push them over the weekend to master. The treedict changes will then be pushed to a target branch. I also managed to include treedict into our own setup.py so that it will install alongside ptypy now.

**Comment by bjoernenders** [comment]
We concluded in the end that treedict will not be made a part of ptypy even though I prefer to avoid recursion in the parameter tree.
