### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#21]
Has to be done at some point.

**Comment by stefanoschalkidis** [comment]
Hi all,

One of the reasons I started working on unittests was to make the code Python 3 compatible. While I first thought it would be good to have all unittests ready before starting the rewrites, I now believe it is better to do them right away because of fresher memory. This is why I would like to discuss and agree on certain Python 3 design choices.

- String ambiguity
There are three ways to approach this:

1. We treat all strings as text data in Python 2 and mark the ones containing binary information. This would retain ambiguity of unmarked strings when run under Python 2.

2. We use unicode_literals to transform all strings in Python 2 to unicode and mark the ones containing binary information. This way we remove the ambiguity.

3. We mark all strings on whether they contain text or binary data.

Here is a small pro & con on unicode_literals:
http://python-future.org/unicode_literals.html

- Rewrites
When rewriting the code I would choose the solution which works better for Python 3, e.g.
`for (key, value) in heights.items():    # inefficient on Py2`
Here is a nice cheat sheet containing a few of such cases:
http://python-future.org/compatible_idioms.html

Let me know what your opinions are on this issue and how you would like the code to evolve.

**Comment by alexbjorling** [comment]
How about just migrating from one release to the next, breaking 2.7 compatibility? It is a bit harsh, but the code will look nicer and be easier to work with. I think people can cope, or do they have ptypy built into other applications?
See also #207

**Comment by jcesardasilva** [comment]
Dear All, 
How is the progress on the port of Ptypy to Python 3? 
I've done a fork and translated all the code as much as I could to Python 3 in terms of syntax. However, it seems that there is a problem with the package utils.descriptor. I thought it was only the ConfigParser problem, since RawConfigParser is deprecated, but not sure. 
If you think it is useful for further progress, I can propose a pullrequest with that version and we could work on top of it. However, I think that maybe someone else already did it. Could we have a branch such as "port2to3" to do it? 
The version I made is not fully working yet. I get the following error message when I try to import the version for Python3 I prepared for ptypy: 
```
---------------------------------------------------------------------------
DuplicateSectionError                     Traceback (most recent call last)
<ipython-input-1-7e5d8b111290> in <module>
----> 1 import ptypy

~/.local/lib/python3.7/site-packages/ptypy/__init__.py in <module>
     73 from . import utils
     74 from . import io
---> 75 from . import experiment
     76 from . import core
     77 from . import simulations

~/.local/lib/python3.7/site-packages/ptypy/experiment/__init__.py in <module>
     18 """
     19 from .. import defaults_tree
---> 20 from ..core.data import MoonFlowerScan, PtydScan, PtyScan, QuickScan
     21 from ..simulations import SimScan
     22 from ..utils.verbose import log

~/.local/lib/python3.7/site-packages/ptypy/core/__init__.py in <module>
      9 """
     10 from .classes import *
---> 11 from .ptycho import *
     12 from .manager import *
     13 from . import xy

~/.local/lib/python3.7/site-packages/ptypy/core/ptycho.py in <module>
     16 from ..utils.verbose import logger, _, report, headerline, log
     17 from ..utils import parallel
---> 18 from .. import engines
     19 from .classes import Base, Container, Storage, PTYCHO_PREFIX
     20 from .manager import ModelManager

~/.local/lib/python3.7/site-packages/ptypy/engines/__init__.py in <module>
     39 
     40 # These imports should be executable separately
---> 41 from . import DM
     42 from . import DM_simple
     43 from . import ML

~/.local/lib/python3.7/site-packages/ptypy/engines/DM.py in <module>
     17 from .base import PositionCorrectionEngine
     18 from .. import defaults_tree
---> 19 from ..core.manager import Full, Vanilla, Bragg3dModel
     20 
     21 __all__ = ['DM']

~/.local/lib/python3.7/site-packages/ptypy/core/manager.py in <module>
     20 from . import sample
     21 from . import geometry
---> 22 from . import data
     23 
     24 from .. import utils as u

~/.local/lib/python3.7/site-packages/ptypy/core/data.py in <module>
   1213 
   1214 @defaults_tree.parse_doc('scandata.PtydScan')
-> 1215 class PtydScan(PtyScan):
   1216     """
   1217     PtyScan provided by native "ptyd" file format.

~/.local/lib/python3.7/site-packages/ptypy/utils/descriptor.py in <lambda>(cls)
   1079         The decorator function.
   1080         """
-> 1081         return lambda cls: self._parse_doc_decorator(name, cls, recursive)
   1082 
   1083     def _parse_doc_decorator(self, name, cls, recursive):

~/.local/lib/python3.7/site-packages/ptypy/utils/descriptor.py in _parse_doc_decorator(self, name, cls, recursive)
   1122         print('\n######################')
   1123         print(parameter_string)
-> 1124         desc.from_string(parameter_string)
   1125 
   1126         # Attach the Parameter group to cls

~/.local/lib/python3.7/site-packages/ptypy/utils/descriptor.py in from_string(self, s, **kwargs)
    404         s = textwrap.dedent(s)
    405         print(s)
--> 406         return self.load_conf_parser(StringIO(s), **kwargs)
    407 
    408     def save_conf_parser(self, fbuffer, print_optional=True):

~/.local/lib/python3.7/site-packages/ptypy/utils/descriptor.py in load_conf_parser(self, fbuffer, **kwargs)
    386         parser = Parser(**kwargs)
    387         # ~ print(list(fbuffer))
--> 388         parser.readfp(fbuffer)
    389         for num, sec in enumerate(parser.sections()):
    390             desc = self.new_child(name=sec, options=dict(parser.items(sec)))

/usr/local/lib/python3.7/configparser.py in readfp(self, fp, filename)
    760             DeprecationWarning, stacklevel=2
    761         )
--> 762         self.read_file(fp, source=filename)
    763 
    764     def get(self, section, option, *, raw=False, vars=None, fallback=_UNSET):

/usr/local/lib/python3.7/configparser.py in read_file(self, f, source)
    715             except AttributeError:
    716                 source = '<???>'
--> 717         self._read(f, source)
    718 
    719     def read_string(self, string, source='<string>'):

/usr/local/lib/python3.7/configparser.py in _read(self, fp, fpname)
   1063                         if self._strict and sectname in elements_added:
   1064                             raise DuplicateSectionError(sectname, fpname,
-> 1065                                                         lineno)
   1066                         cursect = self._sections[sectname]
   1067                         elements_added.add(sectname)

DuplicateSectionError: While reading from '<???>' [line 165]: section 'name' already exists
```

The trouble seems to appear in the descriptor part. Is there anyone already facing this problem? @aaron-parsons @alexbjorling ? I am running python 3.7.0 by the way.

**Comment by aaron-parsons** [comment]
Hi @jcesardasilva,

Bjoern and I were just talking about doing this last week. Thanks for getting started already!

I think you should put your work onto a branch, rather than a fork, and then generate a PR from that branch into master so we can track it. I'll then set up some CI to track where know things break.

If you do this, I'll take a look at the bug with the descriptor. It's a good opportunity to increase testing in that area.

Thanks!

**Comment by jcesardasilva** [comment]
Hi @aaron-parsons 
It seems I cannot create a branch. I am not allowed to do so. Could you please either grant me the right to create it or you create one and I do the pull request on it? Thank you.

**Comment by aaron-parsons** [comment]
Hi, I can't switch which team you are on, but @bjoernenders or @pierrethibault can help us.

**Comment by bjoernenders** [comment]
Hi @jcesardasilva, 
I added you to team ptypy. You should have all the access now that you need. Great that you started making progress. As Aaron suggested, please create a new branch from master, merge with your changes and let as have a look at what you did.
Thanks,
Bjoern

**Comment by jcesardasilva** [comment]
Thank you @bjoernenders 
I did what we discussed and I hope this can help for the port to python3. There are still some problems, such as the one I described here above, but I definitely need help to solve it.

**Comment by bjoernenders** [comment]
We have moved to Python 3 by now.
