### ISSUE TITLE
Limit on number of frames?

### ISSUE THREAD

**Issue by susannahammarberg** [ptycho/ptypy#217]
I'm using @alexbjorling s 3d implementation for Bragg ptycho, and I have a big set of scans that I am trying to reconstruct in 3d, >100 000 frames.

In the output I see:  "Frame 99999 belongs in frame buffer ..."
But after 99 999 it starts doing something else. 

Is there a reason I can not use more frames? 

Thanks!

**Comment by bjoernenders** [comment]
Hi Susanna,

there is a limit to how many frames are being pulled in one call. Originally, this was used to keep preparation overhead low in the streaming version. The limit is placed in line 132 in `manager.py` 
`self.frames_per_call=100000`. You can alter that variable interactively, by settting `Ptycho.model.frames_per_call=xxx` before initialization step 3. Alternatively, since you are working on a fork anyway, you can just change it to a more appropriate value in `manager.py`.

Best, Bjoern

**Comment by susannahammarberg** [comment]
OK, thank you, perfect!

Best,
Sanna
