### ISSUE TITLE
Compilable propagators

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#28]
Propagator is probably the most obvious first step for optimisation. A user switch has to be provided in the input parameters to decide to use compiled or native python code.

**Comment by aaron-parsons** [comment]
We could look at numba for this: http://numba.pydata.org/ . It's been pretty useful for some other applications.

**Comment by jcesardasilva** [comment]
One problem with Numba is it uses LLVM and this has many dependencies. So, the just-in-time (jit) compilation may be easier for the developer but very hard for the user. In addition, installing Numba is not obvious and it is very time-consuming. Further, Numba only works well with Numpy code. See chapter 7 of the book "High performance Python" by M. Gore lick and I. Ozsvald for futher details. If one can, it is better to use Cython instead.

**Comment by aaron-parsons** [comment]
If you build it from source, or use NumbaPro you are right. Otherwise it's just a conda install. Conda also pulls in llvmlite (not the full llvm), but it does it automatically. At least in the installs of it I've done anyway! I'm interested to know if you've had a different experience since we rolled it into other projects so it would be good to know the user experience! Not sure I agree about it only working for numpy though. I've never seen it speed up numpy (it's already fortran and so pretty efficient). It only speeds up basic math such as our realspace update in ptycho. It would never speed up the propagators for instance.

The advantage of it over something like Cython is that you only add the decorator to the existing code, rather than needing to write something new, which makes it maybe more sustainable (less lines of code to cover with tests).

Having said that either is fine by me. It's just an option.

By the way, are you at XRM? It would be nice to meet and chat?

**Comment by jcesardasilva** [comment]
Well, Numba (which is jit) can be simple to use, as well as Shed-Skin, Pythran, PyPy, all are AOT (ahead-of-time compilers) and others, but the only really mature package is Cython. In addition, I don't like to be dependent of Continuum Analytics by using conda, which I don't use, but if I need to do so, I can use it.
I understand that Cython is the hardest for programmers when compared to the others, but it has a stable API that we are sure of work. The others are evolving. I look forward to hearing about the developments of the AOT and JIT technologies, but there have weak points at the moment. 
I will not be able to attend XRM this year, but we can chat in other opportunities.

**Comment by bjoernenders** [comment]
Since we have cuda-capable propagators now, this isn't much of an issue anymore I believe.
