### ISSUE TITLE
add a possible regularization for air/vacuum areas

### ISSUE THREAD

**Issue by jcesardasilva** [ptycho/ptypy#357]
Sometimes, I have cases like the one below in near-field ptycho after several thousands of DM. 
![twitter_f80becfefa9ad78c4c575a3f44630c7d](https://user-images.githubusercontent.com/11873140/127180195-789c3d42-98c1-4a0a-9ea4-4a49f2e8aa2b.jpeg)

The sample is surrounded by air/vacuum on both sides, so it cannot have 2 electron density values as far as I know. 

I am wondering if one could add a regularization term for the air/vacuum areas or another region we know what values of grey-level they should have. This should correct the small phase errors that adds up. I had a short discussion with @pierrethibault by twitter about it. 
I know this also implies the need for a mask of the air/vacuum areas which is supposed to be different for different samples.

**Comment by daurer** [comment]
Hi @jcesardasilva,
Yes, this is certainly possible to do, it's only a question of implementation. I have taken this opportunity to introduce the idea of plugins that I have been discussing with @bjoernenders for a long time. I have implemented two "plugins" for your problem, one for regular DM engine, the other for the GPU-accelerated DM_pycuda engine. 

Please have a look at the `object-mask-regul` branch and this PR: #358 and let me know if this works for you?

Best,
Benedikt

**Comment by jcesardasilva** [comment]
Hi @daurer 

Thank you very much for having implemented this so fast. I've try it, but I have a tiny problem: the value to put in `object_regul_fill`. I tried to put the value `0. +0.j`, which is default, but then it really forces the phases to be 1 in the mask places independent of the rest of the image. I got this weird behaviour with those parameters:

![Capture d’écran 2021-07-29 à 10 24 33](https://user-images.githubusercontent.com/11873140/127458215-7ede2fb2-b008-4181-8236-1fd7f8351b77.png)

Now I need to find a better value to put there or find a way to do something similar to HIO algorithm, which does not impose zeros directly. I don't have the answer now.

**Comment by daurer** [comment]
@jcesardasilva maybe `1+0j` would be a better choice for `object_regul_fill`? This would force the values inside the mask to have amplitude 1 and phase 0. Another option could be to only enforce the regulariser on the phase and keep the amplitudes as they are. I have pushed a change to the `object-mask-regul` branch which effectively does this if you provide a float instead of a complex value as `object_regul_fill`. 

If this is also fails, then you probably need a slightly more advanced algorithm. But hopefully with this idea of plugins, it should be quite easy for you to customize and modify the engine similar to what I did here. It might be of course a bit more tricky to modify the GPU parts, but if you have it working for the CPU engine and it seems useful to more people, we can probably help with the GPU implememtation.

Hope this is helpful,
Benedikt

**Comment by jcesardasilva** [comment]
Thank you again, @daurer. 

Indeed, there are some improvement by using the value `1+0j` relative to `0+0j`, but there are some strange things. The region where the mask is placed shows a flat gray level, not even noise: 

<img width="615" alt="Screenshot 2021-07-29 at 21 05 16" src="https://user-images.githubusercontent.com/11873140/127551428-8c2100c6-238c-482f-acda-2a335e9669db.png">

zooming in a bit.
<img width="623" alt="Screenshot 2021-07-29 at 21 05 33" src="https://user-images.githubusercontent.com/11873140/127551451-2e7b3821-a69e-431e-838e-d72d9ec871ee.png">

I am afraid, except if I mistaken, one needs a more advanced regularisation. Suggestion are the welcome. 
Unfortunately, I will not have time to try new things out now, but I may do it a bit later in the year. Sorry about that. And thank for the offer of help with GPU part, which I appreciate a lot.

**Comment by daurer** [comment]
@jcesardasilva thanks for the feedback. It makes sense that you only see "flat" gray levels because the regulariser enforces those after each object update, that's why there is no noise. As a final tweak, I have now also included start/stop parameters. This way, you could run the regulariser for a given range of iterations but finish the reconstruction without the regulariser. Hopefully, this will give a smoother reconstruction without any flat regions but still with similar phases inside the masked area. 

No worries, this was a good exercise for me to demonstrate how ptypy's core engines can be easily modified. I am still in discussion with @bjoernenders how we are going to integrate these "modifications" into the package, because plugins might not  be the correct idea for this.

**Comment by daurer** [comment]
Closing this issue. A customized engine for the purpose of object regularisation with a mask has been introduced in #358.
