### ISSUE TITLE
About tuning the engines for GPU with low memory

### ISSUE THREAD

**Issue by tingyouli** [ptycho/ptypy#594]
Dear author,

Sorry if this is a stupid question, but I have been bothered by it for many days. I need to tune ptypy for baseline models. And further more, I have limited access to GPU resources, for instance, most of time, just a single **4090 with 24 G graph memory**.

when faced with some large files such as **15G** (40401x220x220) or more,  I know there is a parameter called **frames_per_block** that can be tuned. But the fact is that I tried this parameter to set as 1000, but it still failed with cannot fit into memory after starting the engine. Meanwhile the data loading time before initializing engine is much much longer. **Is there any other parameters that I need to tune to help reduce the memory usage for the algorithm?**  I am currently testing for ePIE. And also I am planning to use DM for baseline as well.

**Comment by daurer** [comment]
Dear @tingyouli,

Unfortunately, frames_per_block is the only parameter that can be tuned to avoid running out of GPU memory. I would suggest to try with something like 100 or even less. Be aware also that frames_per_block should be used together with the scan model "BlockFull" and also that with ePIE you might see artefacts due to the "blocks". With DM the chunking into to blocks is not  an issues.

Hope this helps and do let us know if you need further help!
